CREATE TABLE TASK_EXECUTION_MESSAGE (
    MESSAGE_ID CHAR(36) NOT NULL,
    GROUP_KEY CHAR(36) NOT NULL,
    CREATED_DATE BIGINT NOT NULL,
    MESSAGE_BYTES BLOB,
    MESSAGE_PRIORITY INTEGER,
    REGION VARCHAR(100) NOT NULL,
    PRIMARY KEY (MESSAGE_ID, REGION)
);

CREATE TABLE TASK_EXECUTION_CHANNEL_MESSAGE (
    MESSAGE_ID CHAR(36) NOT NULL,
    GROUP_KEY CHAR(36) NOT NULL,
    CREATED_DATE BIGINT NOT NULL,
    MESSAGE_BYTES BLOB,
    MESSAGE_PRIORITY INTEGER,
    REGION VARCHAR(100) NOT NULL,
    PRIMARY KEY (MESSAGE_ID, REGION)
);

CREATE INDEX TASK_EXECUTION_MSG_DATE_IDX ON TASK_EXECUTION_MESSAGE (CREATED_DATE, MESSAGE_ID);
CREATE INDEX TASK_EXECUTION_GROUP_KEY_IDX ON TASK_EXECUTION_MESSAGE (GROUP_KEY, MESSAGE_ID);
CREATE INDEX TASK_EXECUTION_CHANNEL_MSG_DATE_IDX ON TASK_EXECUTION_CHANNEL_MESSAGE (CREATED_DATE, MESSAGE_ID);
CREATE INDEX TASK_EXECUTION_CHANNEL_GROUP_KEY_IDX ON TASK_EXECUTION_CHANNEL_MESSAGE (GROUP_KEY, MESSAGE_ID);