CREATE TABLE TASK_EXECUTION_MESSAGE (
    MESSAGE_ID CHAR(36) NOT NULL,
    GROUP_KEY CHAR(36) NOT NULL,
    CREATED_DATE BIGINT NOT NULL,
    MESSAGE_BYTES BLOB,
    MESSAGE_PRIORITY INTEGER,
    REGION VARCHAR(100) NOT NULL,
    PRIMARY KEY (MESSAGE_ID, REGION)
);

CREATE TABLE TASK_EXECUTION_CHANNEL_MESSAGE (
    MESSAGE_ID CHAR(36) NOT NULL,
    GROUP_KEY CHAR(36) NOT NULL,
    CREATED_DATE BIGINT NOT NULL,
    MESSAGE_BYTES BLOB,
    MESSAGE_PRIORITY INTEGER,
    REGION VARCHAR(100) NOT NULL,
    PRIMARY KEY (MESSAGE_ID, REGION)
);

CREATE TABLE TASK_EXECUTION (
    TASK_ID BIGINT NOT NULL,
    CORRELATION_ID VARCHAR(36) NOT NULL,
    INVOCATION_ID VARCHAR(36) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    PRIMARY KEY (TASK_ID)
);

CREATE TABLE TASK_EXECUTION_STATE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TASK_ID BIGINT NOT NULL,
    TASK_STATE VARCHAR(20) NOT NULL,
    HTTP_RESPONSE CLOB,
    HTTP_STATUS_CODE INT,
    CREATED_AT TIMESTAMP NOT NULL,
    FOREIGN KEY (TASK_ID) REFERENCES TASK_EXECUTION(TASK_ID)
);

CREATE TABLE INT_LOCK (
    LOCK_KEY CHAR(36) NOT NULL,
    REGION VARCHAR(100) NOT NULL,
    CLIENT_ID CHAR(36),
    CREATED_DATE TIMESTAMP NOT NULL,
    constraint INT_LOCK_PK primary key (LOCK_KEY, REGION)
);

CREATE INDEX TASK_EXECUTION_MSG_DATE_IDX ON TASK_EXECUTION_MESSAGE (CREATED_DATE, MESSAGE_ID);
CREATE INDEX TASK_EXECUTION_GROUP_KEY_IDX ON TASK_EXECUTION_MESSAGE (GROUP_KEY, MESSAGE_ID);
CREATE INDEX TASK_EXECUTION_CHANNEL_MSG_DATE_IDX ON TASK_EXECUTION_CHANNEL_MESSAGE (CREATED_DATE, MESSAGE_ID);
CREATE INDEX TASK_EXECUTION_CHANNEL_GROUP_KEY_IDX ON TASK_EXECUTION_CHANNEL_MESSAGE (GROUP_KEY, MESSAGE_ID);
CREATE INDEX TASK_EXECUTION_STATE_TASK_IDX ON TASK_EXECUTION_STATE (TASK_ID);